#!/usr/bin/env node

if (require.main === module) {
  var express = require('express');
  var bodyParser = require('body-parser');
  var morgan = require('morgan');
  var serveIndex = require('serve-index');
  var serveStatic = require('serve-static');
  var facade = new require(__dirname + '/../');

  var app = express();
  app.use('/', serveStatic(__dirname + '/www'));

  var apiFacade = facade.api.init(__dirname + '/modules');
  app.use('/facade', apiFacade.serve(__dirname + '/templates'));

  app.listen(9000, function() {
    console.log('api server started');
  });
}
