#!/usr/bin/env node

var CLI = new require(__dirname + '/../').cli;
CLI.getOrCreateFacade(__dirname + '/modules', function(facade){
  facade.run({minimist: {string: ["ver"]}}, function(err, res){
    if (err) {
      console.error(err);
    } else {
      console.log(res);
    }
  });
});
