#!/usr/bin/env node

if (require.main === module) {
  var cli = new require('../').cli;
  cli.run(function(res){
    if (res) {
      console.log(res);
    } else {
      console.log("Done");
    }
  });
}
