#!/usr/bin/env node

if (require.main === module) {
  var facade = new require(__dirname + '/../');
  facade.cli.run(__dirname + '/modules', function(res){
    if (res) {
      console.log(res);
    } else {
      console.log("Done");
    }
  });
}
